name: CI-CD pipeline for chatbot

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12.7"

            - name: Setup Buildx Docker
              uses: docker/setup-buildx-action@v2

            - name: Login Docker
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and push Docker
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME}}//rag_chatbot_virat_kohli:latest